Use content type header for a request
flow-php/etl-adapter-http pull request #31
Opened 2021-08-30 17:32 UTC by tomaszhanc

<h2>Change Log</h2>
<div id="change-log">
  <h4>Added</h4>
  <ul id="added">
    
  </ul> 
  <h4>Fixed</h4>  
  <ul id="fixed">
<li>Behavior that was incorrect</li> 
  </ul>
  <h4>Changed</h4>
  <ul id="changed">
    
  </ul>  
  <h4>Removed</h4>
  <ul id="removed">
    
  </ul>
  <h4>Deprecated</h4>
  <ul id="deprecated">
    
  </ul>  
  <h4>Security</h4> 
  <ul id="security">
    
  </ul>     
</div>
<hr/>

<h2>Description</h2>

Current implementation use `Accept` header which defines the response format. When I send an empty request with `Accept` header equals to `application/json` then I receive an error:

```
vendor/flow-php/etl-adapter-http/src/Flow/ETL/Adapter/Http/RequestEntriesFactory.php(52): json_decode()
```

I think we should use the `Content-Type` header to determine the type of a request not the `Accept` header.

2021-08-31 18:48 UTC, norberttech commented
Sorry @tomaszhanc but I'm confused by your solution. 

> Current implementation use Accept header which defines the response format

`Accept` tells the server what content types client is able to understand and IMO it's the right way to guess the request entry type. `Content-Type` is a response header, not request so changing `Accept` to `Content-Type` does not sound right. 

> When I send an empty request with Accept header equals to application/json then I receive an error

I guess what you are looking for is to check the content size and use NullEntry if the content is empty?

2021-08-31 18:48 UTC, norberttech requested changes
Please check my comment

2021-08-31 19:52 UTC, tomaszhanc commented
@norberttech I believe we can use the `Content-Type` header also for a request. If the request has a body we want to specify in which format it is. `Accept` header tells in which format we want to get a response from the server. For example, we can send a multipart request but wanted a JSON format in a response. How would you do that with only the `Accept` header to determine the format of both: request and response? 

I think that using `Accept` to determine the request format might not always be right:
- https://www.ibm.com/docs/en/order-management?topic=services-specifying-http-headers
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

You're right about the support of an empty body request. I'll change that PR tomorrow to support an empty body in a request.

2021-08-31 19:58 UTC, norberttech commented
Right, for POST or PUT with body Content-Type makes more sense than Accept since, client might send body XML but still Accept only JSON. 
I guess the right solution might need to check for existence of Content-Type, then Accept and if Body is empty, use NullEntry no matter what is set.

2021-09-02 05:56 UTC, tomaszhanc commented
@norberttech I pushed the changes. Let me know what do you think

2021-09-02 07:26 UTC, norberttech approved these changes

2021-09-02 07:27 UTC, merged